name: constancia-pytorch
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - streamlit
    - torch
    - numpy
    - pandas
    - yfinance
    - matplotlib
    - scikit-learn
  - conda:
    - cudatoolkit=11.8
