name: constancia-pytorch
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  # ou a versão específica que você precisa
  - pip
  - pip:
    - streamlit
    - torch
    - numpy
    - pandas
    - yfinance
    - matplotlib
    - scikit-learn
  - conda:
    - cudatoolkit=11.8  # Adicione a versão do CUDA compatível com a sua instalação do torch, se necessário
